name: Build APK

on:
  push:
    branches:
      - main  # Change this if your main branch is different
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Specify your Python version

      - name: Install Buildozer and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-pip \
            python3-dev \
            build-essential \
            git \
            zlib1g-dev \
            libffi-dev \
            libssl-dev
          pip install --upgrade buildozer

      - name: Build APK
        run: |
          buildozer -v android debug
